### ISSUE TITLE
读小数不太对

### ISSUE THREAD

**Issue by Yonnemy2nd** [A-kirami/nonebot-plugin-alipayvoice#2]
输入 0.22，0.2，2.2，0.022 的这样的数字都会有些问题，多读 0 或者少读 0，应该是网站的问题。

**Comment by Yonnemy2nd** [comment]
输入整数似乎会后台报错

**Comment by Yonnemy2nd** [comment]
输入整数似乎会报错
onebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 8}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>

**Comment by A-kirami** [comment]
整数问题已修复，小数问题属于网站原因
