### ISSUE TITLE
喵喵喵？

### ISSUE THREAD

**Issue by ID114514** [A-kirami/nonebot-plugin-alipayvoice#4]
[2022-05-18 19:54:36] [WARNING]: 转换CQ码 ({"type": "record", "data": {"file": "https://mm.cqu.cc/share/zhifubaodaozhang/?money=9.0", "magic": null, "cache": null, "proxy": null, "timeout": null}}) 到MiraiGo Element时出现错误: audio type error: text/plain 将忽略本段CQ码.
[2022-05-18 19:54:36] [WARNING]: 群消息发送失败: 消息为空.

**Comment by Warrior-li** [comment]
同出现问题，求问

**Comment by xiaoxianyu233** [comment]
是不是没有装ffmpeg

**Comment by xiaoxianyu233** [comment]
> [2022-05-18 19:54:36] [WARNING]: 转换CQ码 ({"type": "record", "data": {"file": "https://mm.cqu.cc/share/zhifubaodaozhang/?money=9.0", "magic": null, "cache": null, "proxy": null, "timeout": null}}) 到MiraiGo Element时出现错误: audio type error: text/plain 将忽略本段CQ码. [2022-05-18 19:54:36] [WARNING]: 群消息发送失败: 消息为空.

是不是没有装ffmpeg

**Comment by Warrior-li** [comment]
> > [2022-05-18 19:54:36] [WARNING]: 转换CQ码 ({"type": "record", "data": {"file": "https://mm.cqu.cc/share/zhifubaodaozhang/?money=9.0", "magic": null, "cache": null, "proxy": null, "timeout": null}}) 到MiraiGo Element时出现错误: audio type error: text/plain 将忽略本段CQ码. [2022-05-18 19:54:36] [WARNING]: 群消息发送失败: 消息为空.
> 
> 是不是没有装ffmpeg

恕我愚笨，刚刚百度了一下，ffmpeg是直接在linux系统中安装还是要装python对应的包

**Comment by A-kirami** [comment]
> > > [2022-05-18 19:54:36] [WARNING]: 转换CQ码 ({"type": "record", "data": {"file": "[mm.cqu.cc/share/zhifubaodaozhang/?money=9.0](https://mm.cqu.cc/share/zhifubaodaozhang/?money=9.0)", "magic": null, "cache": null, "proxy": null, "timeout": null}}) 到MiraiGo Element时出现错误: audio type error: text/plain 将忽略本段CQ码. [2022-05-18 19:54:36] [WARNING]: 群消息发送失败: 消息为空.
> > 
> > 
> > 是不是没有装ffmpeg
> 
> 恕我愚笨，刚刚百度了一下，ffmpeg是直接在linux系统中安装还是要装python对应的包

请尝试更新插件到最新版查看是否存在相同问题

**Comment by Warrior-li** [comment]
> 

我自己测试了一下，首先是接口本身有一些问题，在您所给出的区间内并不是所有的数字都可以读出（包括不规则整数）。现在已经完成魔改，感谢。
