### ISSUE TITLE
请问哪里错了？

### ISSUE THREAD

**Issue by GC-ZF** [A-kirami/nonebot-plugin-alipayvoice#5]
这个是pip下来直接用的吧？为什么会这样呢
![image](https://user-images.githubusercontent.com/94956933/174936994-5d2cdb24-bb76-4adf-abd2-c20f3bb476e3.png)

**Comment by A-kirami** [comment]
你插件加载的部分写错了
![image](https://user-images.githubusercontent.com/66513481/174941348-b14de91e-58b0-42b9-8b90-c8b90e8440a6.png)
应为 nonebot 而不是 onebot
缺少了开始的 n 字符

**Comment by GC-ZF** [comment]
> 

谢谢！我是智障！问了个这么脑残的问题

**Comment by GC-ZF** [comment]
> 谢谢！我是智障！问了个这么脑残的问题



> 你插件加载的部分写错了 ![image](https://user-images.githubusercontent.com/66513481/174941348-b14de91e-58b0-42b9-8b90-c8b90e8440a6.png) 应为 nonebot 而不是 onebot 缺少了开始的 n 字符

谢谢！我是智障！问了个这么脑残的问题

**Comment by GC-ZF** [comment]
> 你插件加载的部分写错了 ![image](https://user-images.githubusercontent.com/66513481/174941348-b14de91e-58b0-42b9-8b90-c8b90e8440a6.png) 应为 nonebot 而不是 onebot 缺少了开始的 n 字符

谢谢！我是智障！问了个这么脑残的问题
