### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by Passerby-D** [A-kirami/nonebot-plugin-alipayvoice#6]
在本机上这个插件可以正常运行，但换到云服务器上就有报错了
[WARNING]: 转换CQ码 ({"type": "record", "data": {"file": "https://mm.cqu.cc/share/zhifubaodaozhang/mp3/1.mp3", "magic": null, "cache": null, "proxy": null, "timeout": null}}) 到MiraiGo Element时出现错误: encode silk failed: convert pcm file error: exec: "ffmpeg": executable file not found in %PATH% 将忽略本段CQ码.

安装了ffmpeg并设置过环境变量了，在cmd里可以正常调用ffmpeg
在两个机子上操作应该差不多，不知道为什么一个可行另一个就报错了
麻烦大佬看看问题出在哪了

**Comment by A-kirami** [comment]
安装后是否重启了协议端

**Comment by Passerby-D** [comment]
哦哦哦哦哦哦行了
没想到是这么铸币的问题，打扰大佬了
